// sandbox/react/areyousure/confirm.js
import React from 'react';

export const Confirm = React.createClass({
  propTypes: {
    callback: React.PropTypes.func.isRequired,
    disabled: React.PropTypes.bool
  },
  getInitialState() {
    return { confirming: false };
  },
  maybe(){
    this.setState({confirming: true});
  },
  nope(){
    this.setState({confirming: false});
  },
  launch(){
    this.props.callback();
    this.setState({confirming: false});
  },
  componentWillReceiveProps(nextProps){
    if (nextProps.disabled && this.state.confirming){
      this.setState({confirming: false});
    }
  },
  render(){
    if (this.state.confirming){
      return <span>
        <button onClick={this.nope}>Cancel</button>
        <button
          disabled={this.props.disabled}
          onClick={this.launch}>Confirm</button>
      </span>
    } else {
      return <button
        disabled={this.props.disabled}
        onClick={this.maybe}>Submit</button>
    }
  }
});

// sandbox/angular/areyousure/confirm.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'confirm',
  template: `
    <span *ngIf="confirming">
      <button (click)="nope()">Cancel</button>
      <button (click)="launch()">Confirm</button>
    </span>
    <button *ngIf="!confirming" (click)="maybe()" [disabled]="lockButton">Submit</button>
  `
})
export class Confirm {
  confirming = false;
  lockButton = false;
  @Output() confirm = new EventEmitter<void>();
  @Input() set disabled(bool: boolean){
    if (bool){
      this.confirming = false;
    }
    this.lockButton = bool;
  }
  maybe() {
    this.confirming = true;
  }
  nope() {
    this.confirming = false;
  }
  launch() {
    this.confirm.emit();
    this.confirming = false;
  }
}
